version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/projetu"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "/projetu"
    schedule:
      interval: "daily"
