variables:
  ACADEMIC_YEAR:
    value: "2022/2023"
    description: "Academic year in form 'yyyy/yyyy'"
  DOC_NAME:
    value: "booklet_ps6_2022-2023"
    description: "Name of output documents (csv only)"
  PROJECT_TYPE:
    value: "ps6"
    description: "Type of project to build (ps5, ps6 or tb)"
  TAG:
    value: "none"
    description: "Tag projects and use this tag to fetch git project (keep none to not tag projects and fetch last commit on main)"
  OVERRIDE_TAG:
    value: "False"
    description: "Override tag if projects already taged with this tag (True/False)"
  GITLAB_TOKEN: $GITLAB_TOKEN
stages:
  - build

build-kaniko:
  stage: build
  only:
    - tags
  image:
    name: 'gcr.io/kaniko-project/executor:debug'
    entrypoint:
      - ''
  script:
    - >-
      echo
      "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}"
      > /kaniko/.docker/config.json
    - >-
      /kaniko/executor --context $CI_PROJECT_DIR --dockerfile
      $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
      --destination $CI_REGISTRY_IMAGE:latest

create-website:
  image: "registry.forge.hefr.ch/isc/projetu:latest"
  stage: build
  when: manual
  script: 
    - projetu-website-global --template=web_template --type $PROJECT_TYPE --school-year $ACADEMIC_YEAR --output $DOC_NAME --tag $TAG --token $GITLAB_TOKEN --secret $SECRET
  artifacts:
    when: always
    paths:
      - ./*.csv
      - public
      - index.html

pages:
  image: "registry.forge.hefr.ch/isc/projetu:latest"
  stage: build
  when: manual
  script: 
    - projetu-website-global --template=web_template --type $PROJECT_TYPE --school-year $ACADEMIC_YEAR --output $DOC_NAME --tag $TAG --token $GITLAB_TOKEN
  artifacts:
    when: always
    paths:
      - public

tag-projects:    
  image: "registry.forge.hefr.ch/isc/projetu:latest"
  stage: build
  when: manual
  script:
    - projetu-tag --tag $TAG --override $OVERRIDE_TAG --token $GITLAB_TOKEN