stages:
  - build

build-kaniko:
  stage: build
  only:
    - tags
  image:
    name: 'gcr.io/kaniko-project/executor:debug'
    entrypoint:
      - ''
  script:
    - >-
      echo
      "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}"
      > /kaniko/.docker/config.json
    - >-
      /kaniko/executor --context $CI_PROJECT_DIR --dockerfile
      $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
      --destination $CI_REGISTRY_IMAGE:latest

create-booklet:
  image: "registry.forge.hefr.ch/damien.goetschi/projetu:latest"
  stage: build
  when: manual
  script: 
    - projetu-book --page-template=page.md --template=booklet.md --type $PROJECT_TYPE --school-year $ACADEMIC_YEAR --output $DOC_NAME --tag $TAG --token $GITLAB_TOKEN 
    - xelatex $DOC_NAME.tex
    - xelatex $DOC_NAME.tex
    - xelatex $DOC_NAME.tex
    - makeindex $DOC_NAME
    - texindy -L french -C utf8 $DOC_NAME.idx
    - xelatex $DOC_NAME.tex
    - xelatex $DOC_NAME.tex
    - xelatex $DOC_NAME.tex
  artifacts:
    paths:
      - ./*.pdf
      - ./*.csv

tag-projects:
  image: "registry.forge.hefr.ch/damien.goetschi/projetu:latest"
  stage: build
  when: manual
  script:
    - projetu-tag --tag $TAG --overide $OVERRIDE_TAG --token $GITLAB_TOKEN