variables:
  ACADEMIC_YEAR:
    value: "2023/2024"
    description: "Academic year in form 'yyyy/yyyy'"
  DOC_NAME:
    value: "booklet_tb_2023-2024"
    description: "Name of output documents (csv only)"
  PROJECT_TYPE:
    value: "tb"
    description: "Type of project to build (ps5, ps6 or tb)"
  TAG:
    value: "none"
    description: "Tag projects and use this tag to fetch git project (keep none to not tag projects and fetch last commit on main)"
  OVERRIDE_TAG:
    value: "False"
    description: "Override tag if projects already taged with this tag (True/False)"
  GITLAB_TOKEN: $GITLAB_TOKEN
stages:
  - build

build-docker-image:
  stage: build
  only:
    - tags
  image: docker:27.0
  services:
    - docker:27.0-dind
  variables:
    IMAGE_TAG_SLUG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    IMAGE_TAG_LATEST: $CI_REGISTRY_IMAGE:latest
    DOCKER_CLI_EXPERIMENTAL: enabled
  before_script:
    - docker info
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker context create mycontext
    - docker context ls
    - docker buildx create --name mutliarch-builder --use mycontext
    - docker buildx ls
    - docker buildx inspect mutliarch-builder --bootstrap
    - >
      docker buildx build
      --platform linux/amd64,linux/arm64,linux/arm/v7
      --tag $IMAGE_TAG_SLUG
      --tag $IMAGE_TAG_LATEST
      --provenance false
      --push .

create-website:
  image: "registry.forge.hefr.ch/isc/projetu:latest"
  stage: build
  when: manual
  script:
    - projetu-website-global --template=web_template --type $PROJECT_TYPE --school-year $ACADEMIC_YEAR --output $DOC_NAME --tag $TAG --token $GITLAB_TOKEN --secret $SECRET
    - if [ -z ${UPDATE_ASSIGNATIONS_FILE+x} ]; then echo "No assignation file set, build only classic"; else projetu-website-global --template=web_template --type $PROJECT_TYPE --school-year $ACADEMIC_YEAR --output $DOC_NAME --tag $TAG --token $GITLAB_TOKEN --update-assignations $UPDATE_ASSIGNATIONS_FILE; fi
  artifacts:
    when: always
    paths:
      - ./*.csv
      - public
      - index.html

pages:
  image: "registry.forge.hefr.ch/isc/projetu:latest"
  stage: build
  when: manual
  script:
    - projetu-website-global --template=web_template --type $PROJECT_TYPE --school-year $ACADEMIC_YEAR --output $DOC_NAME --tag $TAG --token $GITLAB_TOKEN --secret $SECRET
    - if [ -z ${UPDATE_ASSIGNATIONS_FILE+x} ]; then echo "No assignation file set, build only classic"; else projetu-website-global --template=web_template --type $PROJECT_TYPE --school-year $ACADEMIC_YEAR --output $DOC_NAME --tag $TAG --token $GITLAB_TOKEN --update-assignations $UPDATE_ASSIGNATIONS_FILE; fi
  artifacts:
    when: always
    paths:
      - public

tag-projects:
  image: "registry.forge.hefr.ch/isc/projetu:latest"
  stage: build
  when: manual
  script:
    - projetu-tag --tag $TAG --override $OVERRIDE_TAG --token $GITLAB_TOKEN
