baseURL = "http://example.org/"
languageCode = "en-us"
title = "Projets de semestre 6"
relativeURLs = true
uglyurls = true
theme = "hugo-book"
[permalinks]
 posts = "/:filename/index_"
[taxonomies]
  keyword = 'keywords'
  author = 'author'